name: "go-micro"

x-common-env: &common-env
  env_file:
    - .env

services:
  broker-service:
    <<: *common-env
    container_name: broker-service
    build:
      context: ./../broker-service
      dockerfile: .docker/.Dockerfile-local
    restart: always
    ports:
      - "${BROKER_PORT}:${BROKER_PORT}"
    environment:
      BROKER_PORT: ${BROKER_PORT}
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    <<: *common-env
    container_name: auth-service
    build:
      context: ./../authentication-service
      dockerfile: .docker/.Dockerfile-local
    restart: always
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DNS: host=postgres user=postgres password=password dbname=users port=5432 sslmode=disable TimeZone=Asia/Bangkok
      AUTH_PORT: ${AUTH_PORT}
      POSTGRES_HOST: postgres #using postgres to connect internal service postgres instead of localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      DB_SSLMODE: disable
      DB_TIMEZONE: Asia/Ho_Chi_Minh
    depends_on:
      - postgres

  logger-service:
    <<: *common-env
    container_name: logger-service
    build:
      context: ./../logger-service
      dockerfile: .docker/.Dockerfile-local
    restart: always
    ports:
      - "${LOGGER_PORT}:${LOGGER_PORT}"
    environment:
      LOGGER_PORT: ${LOGGER_PORT}
    deploy:
      mode: replicated
      replicas: 1

  mailer-service:
    <<: *common-env
    container_name: mailer-service
    build:
      context: ./../mail-service
      dockerfile: .docker/.Dockerfile-local
    restart: always
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      MAIL_FROM_NAME: "Thanh Truong"
      MAIL_FROM_ADDRESS: thanh.truong@example.com
      MAILER_PORT: ${MAILER_PORT}
    ports:
      - "${MAILER_PORT}:${MAILER_PORT}"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    <<: *common-env
    container_name: listener-service
    build:
      context: ./../listener-service
      dockerfile: .docker/.Dockerfile-local
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:latest
    container_name: postgres_auth
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres:/var/lib/postgresql

  mongo:
    image: mongo:latest
    container_name: mongo_log
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo:/data/db
    deploy:
      mode: replicated
      replicas: 1

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    # start rabbitmq with management plugin
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      # Management plugin
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq
