name: "go-micro"

services:
  broker-service:
    container_name: broker-service
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/.Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  
  authentication-service:
    container_name: auth-service
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/.Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DNS: host=postgres user=postgres password=password dbname=users port=5432 sslmode=disable TimeZone=Asia/Bangkok
      APP_PORT: 80
      POSTGRES_HOST: postgres #using postgres to connect internal service postgres instead of localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      DB_SSLMODE: disable 
      DB_TIMEZONE: Asia/Ho_Chi_Minh
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    container_name: postgres_auth_service
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres:/var/lib/postgresql